name: Build and upload docs

on:
  push:
    branches: [main, develop, stage]
  pull_request:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
      - name: Build docs
        working-directory: docs
        run: python -m sphinx -b html . _build/html
      - name: Upload pages artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: docs/_build/html
