name: Lint

on:
  push:
    branches: [main, develop, stage]
  pull_request:
    branches: [main, develop, stage]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8

      - name: Run isort check
        run: |
          isort --check-only --profile black .

      - name: Run black check
        run: |
          black --check .

      - name: Run flake8
        run: |
          flake8
