-- 04_create_processed_table.sql
-- Create processed table with structured columns for credit card dataset
CREATE OR REPLACE TABLE creditcard (
    event_time FLOAT,
    v1 FLOAT,
    v2 FLOAT,
    v3 FLOAT,
    v4 FLOAT,
    v5 FLOAT,
    v6 FLOAT,
    v7 FLOAT,
    v8 FLOAT,
    v9 FLOAT,
    v10 FLOAT,
    v11 FLOAT,
    v12 FLOAT,
    v13 FLOAT,
    v14 FLOAT,
    v15 FLOAT,
    v16 FLOAT,
    v17 FLOAT,
    v18 FLOAT,
    v19 FLOAT,
    v20 FLOAT,
    v21 FLOAT,
    v22 FLOAT,
    v23 FLOAT,
    v24 FLOAT,
    v25 FLOAT,
    v26 FLOAT,
    v27 FLOAT,
    v28 FLOAT,
    amount FLOAT,
    class INTEGER,
    load_timestamp TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP (),
    PRIMARY KEY (event_time, load_timestamp)
);
